application: myopenreviews
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: "2.3"

builtins:
- remote_api: on

handlers:
######################################################################
##                  API
## authparams:
##   am: authentication method: "mid", "gsid", "fbid", "twid"
##   at: authentication token (from local or supported external source)
##   an: authentication name (username if native auth, whatever otherwise)
##
## Queries may return a base64 cursor value as the last element.
##
######################################################################

######################################################################
##        MyOpenReviews local site authentication 

## Get an access token from native MyOpenReviews credentials
## POST params: user, pass 
- url: /login.*
  script: src.py.moracct.app

## Create a new native account on MyOpenReviews
## POST params: user, pass, email
- url: /newacct.*
  script: src.py.moracct.app

## Email forgotten native account credentials
## POST params: email
- url: /mailcred.*
  script: src.py.moracct.app

## Change native account password
## POST params: password, authparams
- url: /chgpwd.*
  script: src.py.moracct.app


######################################################################
##        Pen Names

## Fetch pen names for current authentication
## GET params: authparams
- url: /mypens.*
  script: src.py.pen.app

## Create new pen name for current authentication
## POST params: pen, authparams
- url: /newpen.*
  script: src.py.pen.app

## Update a pen name if authorized
## POST params: pen, authparams
- url: /updpen.*
  script: src.py.pen.app

## Upload a profile pic
## POST params: picfilein, _id (PenName instance id), authparams
- url: /profpicupload.*
  script: src.py.pen.app

## Retrieve a profile pic
## GET params: profileid
- url: /profpic.*
  script: src.py.pen.app

## Return pen names containing the qstr text.
## GET params: qstr, cursor, authparams
- url: /srchpens.*
  script: src.py.pen.app

## Return the pen name for the given id.
## GET params: penid
- url: /penbyid.*
  script: src.py.pen.app


######################################################################
##        Relationships

## Find relationships matching the source or target pen id
## GET params: originid, relatedid, offset, cursor, authparams
- url: /findrels.*
  script: src.py.rel.app

## Create new relationship
## POST params: rel, authparams
- url: /newrel.*
  script: src.py.rel.app

## Delete relationship
## POST params: rel, authparams
- url: /delrel.*
  script: src.py.rel.app

## Update relationship
## POST params: rel, authparams
- url: /updrel.*
  script: src.py.rel.app


######################################################################
##        Reviews

## Create a new review for authorized pen name
## POST params: rev, authparams
- url: /newrev.*
  script: src.py.rev.app

## Update review for authorized pen name
## POST params: rev, authparams
- url: /updrev.*
  script: src.py.rev.app

## Delete review for authorized pen name
## POST params: rev, authparams
- url: /delrev.*
  script: src.py.rev.app
  
## Upload a review pic
## POST params: picfilein, _id (Review instance id), authparams
- url: /revpicupload.*
  script: src.py.rev.app

## Retrieve a review pic
## GET params: revid
- url: /revpic.*
  script: src.py.rev.app

## Return reviews for a given pen within the given date range
## GET params: penid, mindate, maxdate, authparams
- url: /srchrevs.*
  script: src.py.rev.app

## Return the review for the given id.
## GET params: revid
- url: /revbyid.*
  script: src.py.rev.app

## Return reviews from any pen name ids in the given csv
## GET params: penids, since, cursor
- url: /revact.*
  script: src.py.rev.app


######################################################################
##        Connection Services

## Return a signed OAuth request given the specified parameters
## POST params: name, posturl, headparams, contentparams
- url: /oa1call.*
  script: src.py.consvc.app

## Return the specified JSON endpoint call results
## GET params: geturl
- url: /jsonget.*
  script: src.py.consvc.app


######################################################################
# Static files and other stuff not really part of the API
#
- url: /cluck2.*
  script: src.py.cluck2.app
- url: /cluck.*
  script: src.py.cluck.app
- url: /testpens
  script: src.py.pen.app
- url: /statrev/\d+
  script: src.py.statrev.app
# Trap anything ending with a slash and send it to index.html since there
# is no default processing to figure that out otherwise.
- url: (.*)/
  static_files: docroot/index.html
  upload: docroot
# Catchall is to look in docroot.
- url: /
  static_dir: docroot
